# Generated by Django 3.2.25 on 2024-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('street_address1', models.CharField(max_length=80)),
                ('town_or_city', models.CharField(max_length=60)),
                ('county', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
    ]
