# Generated by Django 3.2.25 on 2024-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240801_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
